# NUMPY
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
# First import numpy
import numpy as np

## ndarray
Most important data structure in numpy is a type of multi-dimensional array called as ndarray. An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [3]:
# Create one dimension array
arr1 = np.array([0,1,2,3,4])
arr1

array([0, 1, 2, 3, 4])

In [13]:
# want to know type of the data-structure
type(arr1)

numpy.ndarray

In [4]:
# Type of elements in array
arr1.dtype

dtype('int64')

In [91]:
# you can specify data-type of element when you create
arr_type = np.array([0,1,1], dtype='int16')
arr_type.dtype

dtype('int16')

In [5]:
# Number of elements in array
arr1.size

5

In [6]:
# itemsize returns the length of each element of array in bytes.
arr1.itemsize

8

In [62]:
# Get the dimensions of the array
arr1.shape

(5,)

In [8]:
# Create a 2-dimensional array
arr2 = np.array([[5,6,7,8,9], [10,11,12,13,14]])
arr2

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
# array type
type(arr2)

numpy.ndarray

In [9]:
# Type of elements in array
arr2.dtype

dtype('int64')

In [10]:
# Number of elements in array
arr2.size

10

In [11]:
# itemsize returns the length of each element of array in bytes.
arr2.itemsize

8

In [19]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]
arr3=np.array([list1, list2, list3])
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
# Get the dimesions of the array
arr3.shape

(3, 5)

### np ravel 

np ravel function can be used to merge a multi-dimesional array to single dimension array

In [55]:
arr3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Indexing

In [21]:
# Get the first element
arr3[0]

array([1, 2, 3, 4, 5])

In [43]:
type(arr3[0])

numpy.ndarray

In [23]:
# Get the first element
arr3[0][0]

1

In [27]:
# Another indexing format
arr3[0,0]

1

In [47]:
# Give range as index
arr3[1:,1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [50]:
# Negative indexing
arr3[:-1,:-1]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [51]:
# Logical expressions as indexes
arr3[arr3 < 14]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [34]:
arr3.shape

(3, 5)

In [36]:
arr4.shape

(13,)

### NumPy arange()
Numpy arrange function can be used to create multi-dimesional array with range of numbers.

In [54]:
arr5 = np.arange(30)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### Numpy msort
msort function allows us to reorder the elements of array from the lowest value to the highest

In [61]:
arr6 = np.array([16, 67, 1, 23, 46, 999, 4, 78])

In [58]:
np.msort(arr6)

array([  1,   4,  16,  23,  46,  67,  78, 999])

### Numpy reshape
reshape() allows us to reorganize the data of an array into different dimensions. For example: a single dimension array of 8 elements can be converted into 2x4 two dimension array

In [59]:
# Array6 is a ndarray which consists of 8 elements
arr6.shape

(8,)

In [63]:
# can it re-shaped to 4x2
arr6.reshape(4,2)

array([[ 16,  67],
       [  1,  23],
       [ 46, 999],
       [  4,  78]])

In [64]:
# can it re-shaped to 2x4
arr6.reshape(2,4)

array([[ 16,  67,   1,  23],
       [ 46, 999,   4,  78]])

In [66]:
# can it re-shaped to 8x1
arr6.reshape(8,1)

array([[ 16],
       [ 67],
       [  1],
       [ 23],
       [ 46],
       [999],
       [  4],
       [ 78]])

In [68]:
# can it re-shaped to 2x6.. NOPE
arr6.reshape(2,6)

ValueError: cannot reshape array of size 8 into shape (2,6)

### Mathematical operations on array
You can apply calculation on each element of array 

In [77]:
arr7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr8 = arr7 * 10
arr8

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [79]:
arr9 = np.sqrt(arr8)
arr9

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

### Array Stacking and Concatenation
We can concatenate two arrays horizontally or vertically

In [82]:
# Horizontally stack two arrays
arr10 = np.hstack((arr8, arr9))
arr10

array([[10.        , 20.        , 30.        ,  3.16227766,  4.47213595,
         5.47722558],
       [40.        , 50.        , 60.        ,  6.32455532,  7.07106781,
         7.74596669],
       [70.        , 80.        , 90.        ,  8.36660027,  8.94427191,
         9.48683298]])

In [83]:
# Vertically stack two arrays
arr11 = np.vstack((arr8, arr9))
arr11

array([[10.        , 20.        , 30.        ],
       [40.        , 50.        , 60.        ],
       [70.        , 80.        , 90.        ],
       [ 3.16227766,  4.47213595,  5.47722558],
       [ 6.32455532,  7.07106781,  7.74596669],
       [ 8.36660027,  8.94427191,  9.48683298]])

In [85]:
# Concatenate is nothing but vertical stacking
arr12 = np.concatenate((arr8,arr9))
arr12

array([[10.        , 20.        , 30.        ],
       [40.        , 50.        , 60.        ],
       [70.        , 80.        , 90.        ],
       [ 3.16227766,  4.47213595,  5.47722558],
       [ 6.32455532,  7.07106781,  7.74596669],
       [ 8.36660027,  8.94427191,  9.48683298]])

In [87]:
# Concatenate with axis=2 hortizontally stacks arrays
arr13 = np.concatenate((arr8,arr9), axis=1)
arr13

array([[10.        , 20.        , 30.        ,  3.16227766,  4.47213595,
         5.47722558],
       [40.        , 50.        , 60.        ,  6.32455532,  7.07106781,
         7.74596669],
       [70.        , 80.        , 90.        ,  8.36660027,  8.94427191,
         9.48683298]])

In [89]:
arr14 = np.dstack((arr8,arr9))
arr14

array([[[10.        ,  3.16227766],
        [20.        ,  4.47213595],
        [30.        ,  5.47722558]],

       [[40.        ,  6.32455532],
        [50.        ,  7.07106781],
        [60.        ,  7.74596669]],

       [[70.        ,  8.36660027],
        [80.        ,  8.94427191],
        [90.        ,  9.48683298]]])

### Ones and Zeroes function
You can create an array, fill it with all 0s and 1s

In [92]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Randomly distributed array data
If positive, int_like or int-convertible arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

In [98]:
arr_rand=np.random.randn(5,4)
arr_rand

array([[ 0.44358977,  1.5334759 , -0.0325994 , -1.31057247],
       [-0.70473276, -0.04441906,  2.72190469, -0.23429094],
       [ 0.57024349,  0.42956407, -0.82323837, -0.61589378],
       [-0.8616984 ,  0.75356673, -1.34918921, -0.5168391 ],
       [ 0.46788772,  1.46364312, -0.49017707, -1.25328714]])

### Convert to list and pandas dataframe

In [114]:
np.ravel(arr_rand).tolist()

[0.443589771937783,
 1.5334759043012458,
 -0.03259940320627057,
 -1.3105724666938408,
 -0.7047327627917259,
 -0.044419057968038425,
 2.721904691665203,
 -0.23429093844249144,
 0.5702434924362701,
 0.429564072612213,
 -0.8232383714836424,
 -0.6158937829267771,
 -0.8616983991930361,
 0.7535667281817396,
 -1.349189205077884,
 -0.5168390953605385,
 0.4678877222865504,
 1.4636431176536018,
 -0.49017706707438663,
 -1.2532871422027114]

In [115]:
import pandas as pd
df = pd.DataFrame(data=arr_rand.flatten())
df

0
0   0.443590
1   1.533476
2  -0.032599
3  -1.310572
4  -0.704733
5  -0.044419
6   2.721905
7  -0.234291
8   0.570243
9   0.429564
10 -0.823238
11 -0.615894
12 -0.861698
13  0.753567
14 -1.349189
15 -0.516839
16  0.467888
17  1.463643
18 -0.490177
19 -1.253287